[build]
  # Directory to publish (static site output)
  publish = "static-site/"
  # Build command to generate the static site
  command = "node generateSite.js"

# Environment variables for production
[build.environment]
  NODE_ENV = "production"

# Redirect all requests to the static site files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  # Don't redirect actual files
  conditions = {Path = {glob = "!{/images/*,/css/*,/js/*,/*.ico,/robots.txt,/sitemap.xml}"}}

# Add proper cache headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache CSS, JS and images for longer
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404 errors with a custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404